-- AlterTable
ALTER TABLE "tenant_settings" ADD COLUMN     "allow_multiple_chambers" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allow_online_booking" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allow_overlapping_booking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allow_partial_payment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "auto_generate_patient_id" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "custom_config" JSONB,
ADD COLUMN     "enable_digital_signature" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enable_doctor_leave" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enable_doctor_schedule" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enable_email_notification" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enable_insurance_billing" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enable_lab_module" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enable_pharmacy_module" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enable_sms_notification" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "favicon_url" TEXT,
ADD COLUMN     "lab_auto_approve" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lab_report_footer" TEXT,
ADD COLUMN     "max_appointments_per_day" INTEGER,
ADD COLUMN     "medicine_database" TEXT,
ADD COLUMN     "prescription_language" TEXT NOT NULL DEFAULT 'en',
ADD COLUMN     "primary_color" TEXT,
ADD COLUMN     "require_2fa" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "require_birth_certificate" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "require_nid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "secondary_color" TEXT,
ADD COLUMN     "session_timeout_minutes" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "show_doctor_signature" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sms_provider" TEXT,
ADD COLUMN     "tax_percentage" DOUBLE PRECISION,
ALTER COLUMN "language" SET DEFAULT 'bn',
ALTER COLUMN "date_format" SET DEFAULT 'DD-MM-YYYY';

-- CreateIndex
CREATE INDEX "tenant_settings_hospital_id_idx" ON "tenant_settings"("hospital_id");
